version: '3.8'

services:
  db:
    image: postgres:17
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - docker.env
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  postgres_db:
